### ISSUE TITLE
如何自定义封面图？

### ISSUE THREAD

**Issue by imbytecat** [MoeLoli/Diaspora-Typecho#1]
文章页 背景图列表 选择中填写似乎无效，提示：Please set the post thumbnail

**Comment by BapiGso** [comment]
lib-Const.php这个里面把链接换成你的域名或ip，然后在根目录新建一个叫Background的文件夹，图片放进去命名10.jpg好像就行了，不过图片不能自动裁切，编程小白，希望作者大大可以优化下

**Comment by BapiGso** [comment]
> 文章页 背景图列表 选择中填写似乎无效，提示：Please set the post thumbnail

lib里的Const.php这个里面把链接换成你的域名或ip，然后在根目录新建一个叫Background的文件夹，图片放进去命名10.jpg好像就行了，不过图片不能自动裁切，编程小白，希望作者大大可以优化下
