### ISSUE TITLE
出现syntax error, unexpected '}', expecting end of file

### ISSUE THREAD

**Issue by sduwfc** [MoeLoli/Diaspora-Typecho#5]
请问作者我该如何解决这个问题:
当我打开debug模式显示如下:
Notice: Uninitialized string offset: 53 in /www/users/HA623133/WEB/usr/themes/Diaspora-Typecho-master/lib/Content.php on line 63

Notice: Uninitialized string offset: 53 in /www/users/HA623133/WEB/usr/themes/Diaspora-Typecho-master/lib/Content.php on line 63

Notice: Uninitialized string offset: 54 in /www/users/HA623133/WEB/usr/themes/Diaspora-Typecho-master/lib/Content.php on line 63

Notice: Uninitialized string offset: 54 in /www/users/HA623133/WEB/usr/themes/Diaspora-Typecho-master/lib/Content.php on line 63

Notice: Uninitialized string offset: 55 in /www/users/HA623133/WEB/usr/themes/Diaspora-Typecho-master/lib/Content.php on line 63

Notice: Uninitialized string offset: 55 in /www/users/HA623133/WEB/usr/themes/Diaspora-Typecho-master/lib/Content.php on line 63

Notice: Uninitialized string offset: 56 in /www/users/HA623133/WEB/usr/themes/Diaspora-Typecho-master/lib/Content.php on line 63

Notice: Uninitialized string offset: 56 in /www/users/HA623133/WEB/usr/themes/Diaspora-Typecho-master/lib/Content.php on line 63

Notice: Uninitialized string offset: 57 in /www/users/HA623133/WEB/usr/themes/Diaspora-Typecho-master/lib/Content.php on line 63

Notice: Uninitialized string offset: 57 in /www/users/HA623133/WEB/usr/themes/Diaspora-Typecho-master/lib/Content.php on line 63

Notice: Uninitialized string offset: 58 in /www/users/HA623133/WEB/usr/themes/Diaspora-Typecho-master/lib/Content.php on line 63

Notice: Uninitialized string offset: 58 in /www/users/HA623133/WEB/usr/themes/Diaspora-Typecho-master/lib/Content.php on line 63

Notice: Uninitialized string offset: 59 in /www/users/HA623133/WEB/usr/themes/Diaspora-Typecho-master/lib/Content.php on line 63

Notice: Uninitialized string offset: 59 in /www/users/HA623133/WEB/usr/themes/Diaspora-Typecho-master/lib/Content.php on line 63

Notice: Uninitialized string offset: 60 in /www/users/HA623133/WEB/usr/themes/Diaspora-Typecho-master/lib/Content.php on line 63

Notice: Uninitialized string offset: 60 in /www/users/HA623133/WEB/usr/themes/Diaspora-Typecho-master/lib/Content.php on line 63

Notice: Uninitialized string offset: 61 in /www/users/HA623133/WEB/usr/themes/Diaspora-Typecho-master/lib/Content.php on line 63

Notice: Uninitialized string offset: 61 in /www/users/HA623133/WEB/usr/themes/Diaspora-Typecho-master/lib/Content.php on line 63

Notice: Uninitialized string offset: 62 in /www/users/HA623133/WEB/usr/themes/Diaspora-Typecho-master/lib/Content.php on line 63

Notice: Uninitialized string offset: 62 in /www/users/HA623133/WEB/usr/themes/Diaspora-Typecho-master/lib/Content.php on line 63

Notice: Uninitialized string offset: 63 in /www/users/HA623133/WEB/usr/themes/Diaspora-Typecho-master/lib/Content.php on line 63

Notice: Uninitialized string offset: 63 in /www/users/HA623133/WEB/usr/themes/Diaspora-Typecho-master/lib/Content.php on line 63

Notice: Uninitialized string offset: 64 in /www/users/HA623133/WEB/usr/themes/Diaspora-Typecho-master/lib/Content.php on line 63

Notice: Uninitialized string offset: 64 in /www/users/HA623133/WEB/usr/themes/Diaspora-Typecho-master/lib/Content.php on line 63

Notice: Uninitialized string offset: 65 in /www/users/HA623133/WEB/usr/themes/Diaspora-Typecho-master/lib/Content.php on line 63

Notice: Uninitialized string offset: 65 in /www/users/HA623133/WEB/usr/themes/Diaspora-Typecho-master/lib/Content.php on line 63

**Comment by sduwfc** [comment]
只有首页出现这个问题,文章页面可以正常打开.

**Comment by Adoream** [comment]
可以附上你的 PHP 版本吗？

**Comment by me66ccff** [comment]
我也遇见这个问题了，我的PHP版本是7.4.12。
