### ISSUE TITLE
Typecho1.2.1报错

### ISSUE THREAD

**Issue by jrotty** [MoeLoli/Diaspora-Typecho#6]
Typecho1.2.1
php8.2
```
Fatal error: Declaration of Title::label($value) must be compatible with Typecho\Widget\Helper\Form\Element::label(string $value): Typecho\Widget\Helper\Form\Element in /Applications/EServer/www/localhost/usr/themes/diaspora/lib/Title.php on line 13
```

**Comment by Adoream** [comment]
I have adapted to the new interface, but as I don't have a local environment to test it, I would appreciate it if you could try it out and see if there are any remaining issues. Thank you.

**Comment by Adoream** [comment]
I have adapted to the new interface, but as I don't have a local environment to test it, I would appreciate it if you could try it out and see if there are any remaining issues. Thank you.
